name: Release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: Bump
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    name: Ruby gem
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.RELEASE_SSH_KEY }}
      -
        name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      -
        name: Update version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          bundle config unset deployment
          bundle exec rake "version[${{ inputs.semver }}]" && git push
      -
        name: Create tag and push to rubygems
        run: bundle exec rake release
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
